//============================================================================
//  pp_noise54_snd.sv — Namco 54xx noise-generator analog output stage
//
//  NOISE54-2026-08-11. Companion to pp_voice52_snd.sv. The 54xx MCU generates
//  the waveform itself and presents three 4-bit levels (tyre screech, crash,
//  rumble); the board is only DAC + bandpass, so nothing is synthesised here.
//
//  Ground truth: MAME src/mame/namco/polepos_a.cpp CHANL1/2/3 and
//  devices/sound/disc_flt.hxx dst_op_amp_filt, DISC_OP_AMP_FILTER_IS_BAND_PASS_1M.
//
//  ---- channel map (do not shuffle these) -----------------------------------
//      CHANL1 <- NAMCO_54XX_2_DATA = R1 out   -> 2325 Hz, centre gain 2.44
//      CHANL2 <- NAMCO_54XX_1_DATA = O4-O7    ->  232 Hz, centre gain 3.40
//      CHANL3 <- NAMCO_54XX_0_DATA = O0-O3    ->   74 Hz, centre gain 3.65
//
//  ---- per channel, per 48 kHz tick (NOISE54-MFB-2026-09-23) ----------------
//      x = DAC_R1(level) - VREF          (4 V ladder 47k/22k/10k/4.7k, VREF 2.0 V)
//      y = b0*x + b1*x1 + b2*x2 - a1*y1 - a2*y2
//      y = clip(y, -2.0, +1.5)           (op-amp rails 0 / vP-1.5 about VREF)
//      y1 <- CLIPPED y                   (MAME stores after the clip, unlike the engine)
//  The Millman input divider rTotal/r1 is folded into b0..b2. Coefficients are
//  MAME's own formulas at 48 kHz, Q28 — generated by the script at
//  <core>/verilator/noise_filt/mame_noise_ref.py, which is also the test reference.
//  Output = sum(y) * 32768 * (32767/2)/32768 * 0.90 (DISCRETE_OUTPUT + route).
//
//  Replaces the 2026-08-11 crude 1-pole HP+LP stand-in (wrong centres, ~0.5x
//  gain); the previous file is kept as pp_noise54_snd.sv.crude-2026-09-23.
//============================================================================
`default_nettype none

module pp_noise54_snd
(
    input  wire        clk,        // CLK_49M 49.152 MHz (poleposition.vhd's clock_18)
    input  wire        reset,
    input  wire        pause,

    input  wire  [3:0] o0_data,    // discrete_o0 -> CHANL3
    input  wire  [3:0] o1_data,    // discrete_o1 -> CHANL2
    input  wire  [3:0] r1_data,    // discrete_r1 -> CHANL1

    output reg signed [15:0] audio
);

    // ---- 48 kHz tick, same grid as the WSG / engine / 52xx voice -----------
    reg [9:0] tick_div;
    reg       tick;
    always @(posedge clk) begin
        tick <= 1'b0;
        if (reset) begin
            tick_div <= 10'd0;
        end
        else if (!pause) begin
            tick_div <= tick_div + 10'd1;
            if (tick_div == 10'd1023) tick <= 1'b1;
        end
    end

    // ---- units: 1 V = 16384, x/y state carries 8 extra fraction bits (Q8) ----
    localparam signed [35:0] CLIP_HI =  36'sd24576 <<< 8;   // +1.5 V
    localparam signed [35:0] CLIP_LO = -36'sd32768 <<< 8;   // -2.0 V

    // 54xx ladder: (4 V * sum(bit_i * rTotal/R_i)) - VREF, in units
    function automatic signed [17:0] dac(input [3:0] level);
        case (level)
            4'h0: dac = -18'sd32768;   4'h1: dac = -18'sd29094;
            4'h2: dac = -18'sd24918;   4'h3: dac = -18'sd21244;
            4'h4: dac = -18'sd15499;   4'h5: dac = -18'sd11825;
            4'h6: dac = -18'sd7649;    4'h7: dac = -18'sd3975;
            4'h8: dac =  18'sd3975;    4'h9: dac =  18'sd7649;
            4'hA: dac =  18'sd11825;   4'hB: dac =  18'sd15499;
            4'hC: dac =  18'sd21244;   4'hD: dac =  18'sd24918;
            4'hE: dac =  18'sd29094;   default: dac = 18'sd32768;
        endcase
    endfunction

    wire signed [17:0] dac_c1 = dac(r1_data);
    wire signed [17:0] dac_c2 = dac(o1_data);
    wire signed [17:0] dac_c3 = dac(o0_data);

    reg        [1:0]  ch;                                   // 0=CHANL1 1=CHANL2 2=CHANL3
    reg        [2:0]  t;                                    // term 0..5
    reg               busy;
    reg signed [31:0] x0 [0:2];
    reg signed [31:0] x1 [0:2];
    reg signed [31:0] x2 [0:2];
    reg signed [31:0] y1 [0:2];
    reg signed [31:0] y2 [0:2];
    reg signed [63:0] acc;
    reg signed [31:0] out_acc;

    reg signed [31:0] coef;                                 // Q28 (Q20 diverged from MAME under heavy clipping)
    always @(*) begin
        case ({ch, t})
            // CHANL1 (R1): 2325 Hz
            {2'd0,3'd0}: coef = -32'sd47137828;   {2'd0,3'd1}: coef = 32'sd0;
            {2'd0,3'd2}: coef =  32'sd47137828;   {2'd0,3'd3}: coef =  32'sd475273100;   // -a1
            {2'd0,3'd4}: coef = -32'sd229727338;                                          // -a2
            // CHANL2 (O4-O7): 232 Hz
            {2'd1,3'd0}: coef = -32'sd7149718;   {2'd1,3'd1}: coef = 32'sd0;
            {2'd1,3'd2}: coef =  32'sd7149718;   {2'd1,3'd3}: coef =  32'sd532422526;   // -a1
            {2'd1,3'd4}: coef = -32'sd264232598;                                          // -a2
            // CHANL3 (O0-O3): 74 Hz
            {2'd2,3'd0}: coef = -32'sd2409029;   {2'd2,3'd1}: coef = 32'sd0;
            {2'd2,3'd2}: coef =  32'sd2409029;   {2'd2,3'd3}: coef =  32'sd535526948;   // -a1
            {2'd2,3'd4}: coef = -32'sd267116643;                                          // -a2
            default:     coef = 32'sd0;
        endcase
    end

    reg signed [31:0] operand;
    always @(*) begin
        case (t)
            3'd0:    operand = x0[ch];
            3'd1:    operand = x1[ch];
            3'd2:    operand = x2[ch];
            3'd3:    operand = y1[ch];
            default: operand = y2[ch];
        endcase
    end

    wire signed [63:0] prod  = coef * operand;
    wire signed [63:0] acc_r = acc + 64'sd134217728;                // round the Q28 product
    wire signed [35:0] y_new = acc_r[63:28];                        // Q8 units
    wire signed [35:0] y_c36 = (y_new > CLIP_HI) ? CLIP_HI : (y_new < CLIP_LO) ? CLIP_LO : y_new;
    wire signed [31:0] y_cl  = y_c36[31:0];
    // weight: 32768 * (32767/2)/32768 * 0.90 / 16384 = 0.9 -> 3686 Q12, and >>> 8 for the Q8 state
    wire signed [44:0] wprod = y_cl * 13'sd3686;                    // 13 bits: 3686 > 12-bit signed max
    wire signed [31:0] out_next = out_acc + {{12{wprod[44]}}, wprod[39:20]};

    integer k;
    always @(posedge clk) begin
        if (reset) begin
            busy <= 1'b0; ch <= 2'd0; t <= 3'd0; acc <= 64'sd0; out_acc <= 32'sd0; audio <= 16'sd0;
            for (k = 0; k < 3; k = k + 1) begin
                x0[k] <= 32'sd0; x1[k] <= 32'sd0; x2[k] <= 32'sd0; y1[k] <= 32'sd0; y2[k] <= 32'sd0;
            end
        end else if (!busy) begin
            if (tick) begin
                x0[0] <= {{6{dac_c1[17]}}, dac_c1, 8'd0};
                x0[1] <= {{6{dac_c2[17]}}, dac_c2, 8'd0};
                x0[2] <= {{6{dac_c3[17]}}, dac_c3, 8'd0};
                busy <= 1'b1; ch <= 2'd0; t <= 3'd0; acc <= 64'sd0; out_acc <= 32'sd0;
            end
        end else if (t != 3'd5) begin
            acc <= acc + prod;
            t   <= t + 3'd1;
        end else begin
            x2[ch] <= x1[ch];
            x1[ch] <= x0[ch];
            y2[ch] <= y1[ch];
            y1[ch] <= y_cl;                                         // clipped, as MAME
            acc    <= 64'sd0;
            t      <= 3'd0;
            if (ch == 2'd2) begin
                busy  <= 1'b0;
                audio <= (out_next >  32'sd32767) ? 16'sh7FFF :
                         (out_next < -32'sd32768) ? 16'sh8000 : out_next[15:0];
            end else begin
                out_acc <= out_next;
                ch      <= ch + 2'd1;
            end
        end
    end

endmodule

`default_nettype wire
